### ISSUE TITLE
binary releases?

### ISSUE THREAD

**Issue by hrj** [gnieh/tiscaf#10]
Would be nice if the binary releases were downloadable.

Thanks!

**Comment by satabin** [comment]
Hi,

Tiscaf is published on sonatype repository (see instructions here https://github.com/gnieh/tiscaf/wiki/Installation) For snapshot version, you need to add the sonatype snapshot resolver.

If you are using neither sbt nor maven (nor any other tool understanding maven repositories), you can always download jar files here: https://oss.sonatype.org/content/repositories/releases/org/gnieh/

**Comment by hrj** [comment]
Thanks. That helps and probably should be mentioned in the README. 

Aside, Github has a release feature, and you can attach release notes and binaries to each release. You can consider using it if you like.

**Comment by satabin** [comment]
The README already mentions that documentation and tutorial is present in the wiki part. I don't want the README to be the documentation of the project, just an introduction to it.

Besides, I don't manage my releases with github release feature.

I started to try it on [sohva for the last release](https://github.com/gnieh/sohva/releases/tag/0.5) but I'm no huge fan of uploading binaries on github when you have tools for the technology that already exist to manage dependencies. Tiscaf is not a standalone product, it's a library. If it were a product I would have uploaded it on github to download it manually.
