### ISSUE TITLE
Debug prints

### ISSUE THREAD

**Issue by hrj** [gnieh/tiscaf#11]
Looks like the core emits debug prints:

```
tiscaf server was started on port(s) 8910
tiscaf stop listener is listening to port 8911
Task submitted to plain peer
Task submitted to plain peer
```

**Comment by satabin** [comment]
Please see my last comment on ticket #8
You can override this behavior to log wherever you want (or just ignore the messages).

**Comment by hrj** [comment]
Ah ok. I think the default for info should be silent. Warnings and errors can be logged by default.

**Comment by hrj** [comment]
Further, I think the "server starting" messages could be called "info" (turned on by default) and the "Task submitted" messages could be called "debug" and turned off by default.
