### ISSUE TITLE
Response gets truncated

### ISSUE THREAD

**Issue by kincsescsaba** [gnieh/tiscaf#14]
It works until it gets bigger. In my case I only get the first 34kB of a ~50kB response on the client side. Not sure if some bogus character could cause it

**Comment by kincsescsaba** [comment]
UPDATE: rechecked it, only last 2-3 chars are truncated but still don't know why

**Comment by kincsescsaba** [comment]
UPDATE: if I use this quick and dirty solution:

``` scala
talk.setContentLength(resp.length + 2).setCharacterEncoding("UTF-8")
        .setContentType("application/json")
        .write(resp)
```

then it works but something is still wrong and this may cause another error elsewhere

**Comment by satabin** [comment]
What is the content of `resp`? Do you have non ASCII characters? These can be encoded on more than one byte, and `length` returns the number of characters, not bytes.

**Comment by satabin** [comment]
Does it work if you write:

``` scala
val bytes = resp.getBytes("UTF-8")
talk.setContentLength(bytes.length)
        .setContentType("application/json")
        .write(bytes)
```

**Comment by kincsescsaba** [comment]
Hi Lucas! Thanks for help, now it seems to work, I will continue testing,
hopefully no more troubles will occur.
For your question: resp contains Twitter REST API data which was previously
cached on disk and then reloaded

Cheers,
Csaba

Lucas Satabin notifications@github.com ezt írta (2015. szeptember 30.,
szerda):
