### ISSUE TITLE
Tiscaf no longer available on maven?

### ISSUE THREAD

**Issue by jukowski** [gnieh/tiscaf#5]
In https://github.com/gnieh/tiscaf/wiki/Installation suggests that the library should be available in the central maven repository. This is, however, not the case. Do I need to add maybe another repository to my pom.xml?

Thanks

**Comment by satabin** [comment]
Hi,

Sorry for the late answer. Tiscaf is not yet released, so it is only available in the snapshot repository. You need to add https://oss.sonatype.org/content/repositories/snapshots/ as repository.
