### ISSUE TITLE
POST/application/x-www-form-urlencoded params decoding issue

### ISSUE THREAD

**Issue by ornicar** [gnieh/tiscaf#7]
Hello and thanks for tiscaf, I'm using it to power http://river.scalex.org

I noticed an issue with x-www-form-urlencoded post data. When accessing it from `HReqData`, at the time it reaches https://github.com/gnieh/tiscaf/blob/master/src/main/scala/tiscaf/HReqData.scala#L109, it is already decoded.

Now two things can happen. If the data contains a `%` character, the decoding will fail. This is good because like I said, the data is already decoded. So we get it intact.

But, if the data does not contain `%`, then we get into trouble. It gets decoded a second time. As a result, `+` chars get replaced with spaces.

To reproduce it, send some post data containing a `+` to a tiscaf application:

``` sh
curl localhost:8098 --data-urlencode source='1 + 1'
```

if you print the data accessed from the application:

``` scala
println(talk.req.softParam("source"))
```

you'll see:

```
1   1
```

Now if you add a `%` char, then the string is good:

``` sh
curl localhost:8098 --data-urlencode source='1 + 1 %'
```

prints as

```
1 + 1 %
```

I couldn't quickly decide where in tiscaf the fix should go.

**Comment by satabin** [comment]
HI @ornicar 

Sorry for the late answer. The problem with the '+' decoded twice was spotted in the last published version and I thought it was fixed by now. What version of tiscaf are you using?

**Comment by satabin** [comment]
BTW, nice use case! We should release a new version soon that will be available through sbt, this kind of feedback is highly welcome :)

**Comment by satabin** [comment]
Ok the problem was the same as it was with `param` in the last release. Somehow we missed the fix for `softParam`.

Thanks for reporting

**Comment by ornicar** [comment]
Thanks for fixing!
