### ISSUE TITLE
POST/application/x-www-form-urlencoded size limitation

### ISSUE THREAD

**Issue by ornicar** [gnieh/tiscaf#8]
It looks like there is a quite low limit (around 2KB, I didn't check thoroughly) for POST data.

``` sh
curl localhost:8098 --data-urlencode source@/path/to/someBigFile
```

fails with:

```
curl: (52) Empty reply from server
```

regardless the usage of the `source` param. No error is visible in sbt console.

**Comment by ornicar** [comment]
using 0.8-SNAPSHOT

This bug did exist before the encoding recent bugfix.

**Comment by satabin** [comment]
Did you try to override `maxPostDataLength` in `Hserver` (should be used for POST other than multipart/form-data)?
Default is `65536`

**Comment by ornicar** [comment]
Shame on me. That was it.

Maybe an informational message in the server stdout would help.

Thank you for your time.

**Comment by satabin** [comment]
I am always reluctant to add hard-coded messages to stdout in such a piece of software but you are right. I should put some effort on the logging side in tiscaf.

The concept of tiscaf is to have a small HTTP server that depends on nothing, thus I should probably model a simple logging API that print to stdout by default and can be overridden by users to use their favorite logging library. I opened #9 for this
